### ISSUE TITLE
Komplettering, Laboration 1

### ISSUE THREAD

**Issue by 1dv449** [ss223ck/1DV449_ss223ck#1]
Komplettera laboration ett genom att publicera en fungerade version i en driftsmiljö. Svara här när du är klar. Testa applikationen mot:
http://46.101.232.43/

**Comment by ss223ck** [comment]
http://sverker.ddns.net/lab_1/
Fungerar nu. Hostar hemifrån så meddela gärna när du kollat så jag kan stänga ner mina portar

**Comment by 1dv449** [comment]
OK, ser ut att funka som det ska
